sudo: false

language: node_js

node_js:
  - 12

cache: npm

branches:
  only:
    - source # build source branch only

before_install:
  - export TZ='Asia/Shanghai'
  - sudo apt-get -y install libsass-dev

addons:
  apt:
    update: true

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g # generate static files

after_script:
  - cd ./public
  - git init
  - git config user.name "sparrowhole"
  - git config user.email "${EMAIL}"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@${REPO}" master:master
